### PR TITLE
fix: adjust window position for monitor DPI

### PR DESCRIPTION
**Pull request by JonasWischeropp**
1. Logical needs to be converted into Physical
2. `anchor_<x|y>` ([line 246](https://github.com/glzr-io/zebar/blob/badd5312c9e2e9ea2784bc63902cbd9ec1af4187/packages/desktop/src/widget_factory.rs#L246)) is already a PhysicalPosition 
# Example:
Monitor: 1600px 900px with 150%
```json
  "defaultPlacements": [
    {
      "anchor": "bottom_left",
      "offsetX": "0px",
      "offsetY": "-24px",
      "width": "100%",
      "height": "24px",
      "monitorSelection": {
        "type": "all"
      }
    }
  ]
```
Before the y-position was calculated by  `(1600+-24)*(2/3)` and not by `1600+(-24*(3/2))`.

I think that #115 might be related to this.

### CODE REVIEW

**Comment by lars-berger** [comment]
Ay thanks for the PR on this 🙏 

It's so close to everything positioning nicely... but I was still able to reproduce a scaling issue with the default starter configs on one of the monitors like so:

Screenshot 2024-10-02 052646

image
image

**Comment by lars-berger** [comment]
Seems to work correctly if size/position is set twice:
```rust
#[cfg(target_os = "windows")]
{
  let _ = window.set_size(size);
  let _ = window.set_position(position);
  let _ = window.set_size(size);
  let _ = window.set_position(position); // < not sure whether this call is necessary or if it's only size that needs to be set twice
}
```
We do something similar in GlazeWM where we call `SetWindowPos` twice when doing cross-monitor moves with different DPI's.

Are you able to reproduce #116 btw? Wonder if this also fixes that issue

**Comment by JonasWischeropp** [comment]
After some testing, I was able to reproduce #116.
The bar was rendered outside of the monitor.

With the adjustments of this PR, the problem no longer occurred (with and without calling `window.set_size` and `window.set_position` twice).

**Comment by JonasWischeropp** [comment]
I was unable to reproduce any problems that require to set size and position twice.

**Comment by JonasWischeropp** [comment]
Never mind, I was able to reproduce the same problem you mentioned.
And with `set_size` and `set_position` twice it was fixed. Good catch, I would never have thought of that.

**Comment by JonasWischeropp** [comment]
> BTW, I think we should be scaling only pixel values and leaving % values (e.g. `"width": "98%"`) untouched. Does that sound right? Otherwise, e.g. `98%` ends up scaling to the full size of the monitor

Makes sense, I hadn't thought of that. I will make the change.

**Comment by JonasWischeropp** [comment]
Percentage values are no longer scaled.

**Pull request merged**
