### PR TITLE
feat: add media provider

### PR DESCRIPTION
**Pull request by HolbyFPV**
Adds media provider using WinAPI GlobalSystemMediaTransportControls.

Big thanks to @Irilith for #126 and allowing me to use the `client-api` code.

### CODE REVIEW

**Comment by HolbyFPV** [comment]
Closes #73

**Comment by DreamMaoMao** [comment]
Is there a configuration demonstration file that shows how to use it?

**Comment by mdxwzl** [comment]
Are you going to implement this Feature for macOS & ubuntu too?

**Comment by HolbyFPV** [comment]
@DreamMaoMao The provider is called `media` and can be used like other providers:
```
const providers = zebar.createProviderGroup({
  media: { type: 'media' },
});

<div class="chip">Media: {output.media?.artist}</div>
```
The available options right now are:
```
title: string;
artist: string;
album: string;
albumArtist: string;
trackNumber: number;
startTime: number;
endTime: number;
position: number;
isPlaying: boolean;
```
`startTime`, `endTime`, and `position` are in seconds.  For `mm:ss` format, you can do something like mm:`postion / 60` and ss:`position % 60`.

@mdxwzl Currently only available on Windows.  The Mac/Linux versions are free to grab if anyone would like to work on that.

There's also no support yet for interaction (having buttons for play/next song/ect..), but we are looking into making this possible.

**Comment by DreamMaoMao** [comment]
image

@HolbyFPV 

seem not work.

**Comment by HolbyFPV** [comment]
@DreamMaoMao 

Try the boiler-plate-solidts\example config, should look something like this displaying the artist:
image

**Comment by DreamMaoMao** [comment]
image

@HolbyFPV

**Comment by HolbyFPV** [comment]
@DreamMaoMao Are you running with `pnpm dev`?

**Comment by DreamMaoMao** [comment]
> @DreamMaoMao Are you running with `pnpm dev`?

no i just:

start zebar and do nothing

**Comment by HolbyFPV** [comment]
@DreamMaoMao 

If you have the branch checked out locally, try running `pnpm dev` to start zebar.  The code your looking for is in `zebar\examples\boilerplate-solid-ts\src\index.tsx`.

**Comment by DreamMaoMao** [comment]
> @DreamMaoMao
> 
> If you have the branch checked out locally, try running `pnpm dev` to start zebar. The code your looking for is in `zebar\examples\boilerplate-solid-ts\src\index.tsx`.

my network can use npm, so i just use 'bun i && bun run build'

and now it get the same error with react

`
image

**Pull request merged**
