### PR TITLE
chore: upgrade Komorebi client to v0.1.26

### PR DESCRIPTION
**Pull request by CtByte**
I intend to address an issue that is now fixed with Komorebi and Stackbar, as @LGUG2Z was kind enough to create a new release when this issue was fixed, just to make things faster.

This also helps those who upgrade Komorebi to a higher version compared to what is currently being used by Zebar, see #52.

### CODE REVIEW

**Comment by adriankarlen** [comment]
I'm not sure if komorebi is using semantic versioning but would it not make sense to wildcard the minor version, assuming that it is not a breaking change most of the time?

Perhaps @LGUG2Z can give some clarity on the versioning of komorebi, but it feels unsustainable to keep bumping for every bugfix in komorebi.

**Comment by LGUG2Z** [comment]
These are not bugfix releases; the last few releases have seen some major changes to the state format with the introduction of features like the Stackbar.

What I think makes sense here is for Zebar and other integrators who only care about a small subset of the state to wrap the notifications received in structs that only specify the fields they are interested in, and then deserialize the notifications to that struct.

**Comment by CtByte** [comment]
I can see that I should have clarified the purpose of this PR in the description. I will fix that now. 

I agree that the Komorebi integration could be more flexible as to what fields to map. In this particular case, the new Komorebi version also added a new layout type that is probably better to include, rather than make a workaround to ignore it.

**Comment by LGUG2Z** [comment]
Might as well bump this PR to tag `v0.1.26` now

**Comment by CtByte** [comment]
Sure, I will test it a bit first 😉

**Comment by LGUG2Z** [comment]
Might as well bump this PR to tag `v0.1.27` now 😅

**Pull request merged**
